version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: frontend
    image: frontend

    ports:
      - '3000:3000'
    stdin_open: true
    tty: true